export const users = [
  {
    name: 'Ced',
    email: 'ced@ced.com',
    avatar: 'avatar',
    type: 'artist',
    gender: 'male',
    active: true,
    password: 'test1234',
    passwordConfirm: 'test1234',
    __v: 0,
  },
  {
    name: 'Dan',
    email: 'dan@dan.com',
    avatar: 'avatar',
    type: 'streamer',
    gender: 'female',
    active: true,
    password: 'test1234',
    passwordConfirm: 'test1234',
    __v: 0,
  },
  {
    name: 'John',
    email: 'john@doe.com',
    avatar: 'avatar',
    type: 'artist',
    gender: 'male',
    active: true,
    password: 'test1234',
    passwordConfirm: 'test1234',
    __v: 0,
  },
];

export const payload = {
  name: 'John',
  email: 'john@doe.com',
  avatar: 'avatar',
  type: 'artist',
  gender: 'male',
  active: true,
  password: 'test1234',
  passwordConfirm: 'test1234',
  __v: 0,
};
